const mongoose = require('mongoose');

const commentSchema = new mongoose.Schema({

  // Which user created this comment
  userId: { 
    type: mongoose.Schema.Types.ObjectId, 
    ref: 'User', 
    required: true 
  },

  // instagram or facebook
  platform: { 
    type: String, 
    enum: ['instagram', 'facebook'], 
    required: true 
  },

  // The ID of the post we're commenting on (from Meta API)
  postId: { 
    type: String, 
    required: true 
  },

  // Optional - the full URL of the post
  postUrl: { 
    type: String 
  },

  // The actual comment text
  commentText: { 
    type: String, 
    required: true 
  },

  // Current status of this comment
  status: { 
    type: String, 
    enum: ['pending', 'sent', 'failed'], 
    default: 'pending' 
  },

  // When to post it (for scheduled comments)
  scheduledAt: { 
    type: Date 
  },

  // When it was actually posted
  sentAt: { 
    type: Date 
  },

  // If posting failed, why?
  errorMessage: { 
    type: String 
  },

  // Was this comment generated by AI?
  isAiGenerated: { 
    type: Boolean, 
    default: false 
  },

  createdAt: { 
    type: Date, 
    default: Date.now 
  }

});

module.exports = mongoose.model('Comment', commentSchema);